### ISSUE TITLE
System.DllNotFoundException

### ISSUE THREAD

**Issue by ctrlaltdude** [FreekDS/MSI-Mystic-Light-Controller#2]
Hi Freek,

I keep running into this exception:
Exception thrown: 'System.DllNotFoundException' in MysticLightController.dll
An unhandled exception of type 'System.DllNotFoundException' occurred in MysticLightController.dll
Unable to load DLL 'MysticLight_SDK.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)

Any idea what could cause this? I have the latest MSI Dragon software with Mystic Lights installed.
When I try to import the MysticLight_SDK.dll into my Visual Studio project I get an error that it is not a type or version this project can use. The SDK documentation mentions nothing about any dependencies other than "MSI Mystic Light related applications must be installed before using the SDK function".

I've tried all I could think of, even dependency walker for the MysticLight_SDK.dll, but something seems to be missing and it doesn't tell what. 

Grtz,
Hans

**Comment by ctrlaltdude** [comment]
Uuh I found the issue :s
I included the filename in the path which was not the way.
(LightController controller = new LightController("C:\\temp\\mysticlight\\");)

But now I run into the issue it doesn't find a device. So I guess my TRX40 mainboard is not compatible.
(System.IndexOutOfRangeException' occurred in MysticLightController.dll)

**Comment by FreekDS** [comment]
Sad to hear it is not compatible, if you find a way to get it working, you can definetly let me know!
